remove ppx_import dependency
ppx_import requires staged_pps, which causes compilation to fail on
Windows:

'.ppx' is not recognized as an internal or external command,
operable program or batch file.
File "src/eon_parser/parser__mock.ml.mock", line 1:
Error: Error while running external preprocessor